#!/usr/bin/env bash
# compose.sh: lay the core SDK's cgo package main under this directory's messaging half, so that
# `go build -buildmode=c-shared .` here builds the one native library both halves ship in.
#
#   bash sdk/cgo/compose.sh [core-sdk-root]   compose (default core root: ../sdk beside this repository)
#   bash sdk/cgo/compose.sh --clean           remove what a compose added, and nothing else
#
# WHY A COMPOSITION AND NOT A DEPENDENCY. The C ABI is one library, URnetworkSdk, and its package
# main is the core SDK's (urnetwork/sdk cgo/): the handle table, the C-string helpers, cgoGuard and
# the generated exports. The messaging half (exports_message.go, callbacks_message.{c,h} and
# include/urnetwork_message.h) calls those helpers, and a package main cannot be imported, so the
# two halves can only meet as files of one directory. This script puts the core's files beside
# this repository's, for a build, and records exactly what it put there.
#
# WHAT IT COPIES: every non-test .go, .c and .h file at the root of the core's cgo/ directory, and
# the core's include/urnetwork_sdk.h and include/urnetwork_sdk.hpp. NOT the core's .def: the
# library's .def is this directory's include/urnetwork_sdk.def, the core's entries and the
# messaging exports together, generated by `go run ./gen` and held current by gen's tests.
#
# WHAT IT REFUSES:
#   - a core whose cgo/ still holds the messaging half (exports_message.go or
#     callbacks_message.c): that is a core from before the sdk removal, and composing it would put
#     every messaging export in the library twice;
#   - a file that already exists here: a tracked file of this repository is never overwritten, and
#     a second compose over a first is refused rather than mixed (clean first);
#   - a core directory that is not there;
#   - a core whose files are not exactly the list in sdk/cgo/.gitignore, between "# composed-begin"
#     and "# composed-end": that list is what keeps a composed tree's `git add -A` from committing
#     the core's package main, so it is held to what is laid down, both ways, before anything is.
# The list of what it copied is .composed (gitignored), with the core commit when the core is a git
# checkout; --clean reads it back and removes exactly those paths.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
record="$here/.composed"

if [ "${1:-}" = "--clean" ]; then
  if [ ! -f "$record" ]; then
    echo "compose: nothing to clean ($record is absent)"
    exit 0
  fi
  removed=0
  while IFS= read -r line; do
    case "$line" in
      "#"*|"") continue ;;
    esac
    rm -f -- "$here/$line"
    removed=$((removed + 1))
  done < "$record"
  rm -f -- "$record"
  echo "compose: removed $removed composed file(s)"
  exit 0
fi

core=${1:-$here/../../../sdk}
if [ ! -d "$core/cgo" ]; then
  echo "compose: $core/cgo is not a directory; check out urnetwork/sdk at the pinned commit beside this repository" >&2
  exit 1
fi
core=$(cd "$core" && pwd)
for marker in exports_message.go callbacks_message.c; do
  if [ -e "$core/cgo/$marker" ]; then
    echo "compose: $core/cgo holds $marker, the messaging half; that core predates the sdk removal and would export every messaging symbol twice" >&2
    exit 1
  fi
done
if [ -e "$record" ]; then
  echo "compose: $record exists; this directory is already composed (run bash sdk/cgo/compose.sh --clean first)" >&2
  exit 1
fi

files=()
for path in "$core"/cgo/*.go "$core"/cgo/*.c "$core"/cgo/*.h; do
  [ -f "$path" ] || continue
  name=$(basename "$path")
  case "$name" in
    *_test.go) continue ;;
  esac
  files+=("$name")
done
for name in urnetwork_sdk.h urnetwork_sdk.hpp; do
  files+=("include/$name")
done
if [ "${#files[@]}" -eq 0 ]; then
  echo "compose: $core/cgo holds no package-main source" >&2
  exit 1
fi
for name in "${files[@]}"; do
  if [ ! -f "$core/cgo/$name" ]; then
    echo "compose: the core has no cgo/$name" >&2
    exit 1
  fi
  if [ -e "$here/$name" ]; then
    echo "compose: $name already exists in sdk/cgo; refusing to overwrite it" >&2
    exit 1
  fi
done
listed=$(sed -n '/^# composed-begin$/,/^# composed-end$/p' "$here/.gitignore" | tr -d '\r' | grep -v '^#' | sed 's#^/##' | sort)
laying=$(printf '%s\n' "${files[@]}" | sort)
if [ -z "$listed" ] || [ "$listed" != "$laying" ]; then
  echo "compose: sdk/cgo/.gitignore's composed list is not what this core lays down (< listed only, > laid down only):" >&2
  diff <(printf '%s\n' "$listed") <(printf '%s\n' "$laying") >&2 || true
  echo "compose: update the list between '# composed-begin' and '# composed-end' in sdk/cgo/.gitignore" >&2
  exit 1
fi

commit=$(git -C "$core" rev-parse HEAD 2>/dev/null || echo "not a git checkout")
{
  echo "# composed by sdk/cgo/compose.sh from $core (commit $commit)"
  for name in "${files[@]}"; do
    echo "$name"
  done
} > "$record"
for name in "${files[@]}"; do
  cp -- "$core/cgo/$name" "$here/$name"
done
echo "compose: ${#files[@]} core file(s) laid under sdk/cgo from commit $commit"
